name: CI

on: [push, pull_request]

jobs:
  build-and-test-core:
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [8, 11]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Enable git support for long paths on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - uses: actions/checkout@v2

      - name: Set up OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.javaVersion }}
          settings-path: ${{ github.workspace }}

      - name: Build & Test Core
        shell: bash
        run: |
          mvn install -f cobigen --projects !cobigen-core-systemtest -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  build-and-test-plugins:
    needs: build-and-test-core
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [8, 11]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Enable git support for long paths on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - uses: actions/checkout@v2

      - name: Set up OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.javaVersion }}
          settings-path: ${{ github.workspace }}

      - name: Build & Test Plugins
        shell: bash
        run: |
          mvn install -f cobigen-plugins -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  build-plugins-p2:
    needs: build-and-test-plugins
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - uses: actions/cache@v2.1.5
        with:
          path: ./**/target/repository/
          key: p2-${{ github.sha }}

      - name: Enable git support for long paths on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - uses: actions/checkout@v2

      - name: Set up OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.javaVersion }}
          settings-path: ${{ github.workspace }}

      - name: Build Plugins UpdateSite
        shell: bash
        run: |
          mvn package -DskipTests -f cobigen-plugins bundle:bundle -Pp2-bundle --projects !cobigen-javaplugin-parent/cobigen-javaplugin-model,!cobigen-openapiplugin-parent/cobigen-openapiplugin-model,!:plugins-parent,!cobigen-javaplugin-parent,!cobigen-openapiplugin-parent,!cobigen-templateengines -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          mvn install -DskipTests -f cobigen-plugins bundle:bundle -Pp2-bundle p2:site --projects !cobigen-javaplugin-parent/cobigen-javaplugin-model,!cobigen-openapiplugin-parent/cobigen-openapiplugin-model,!:plugins-parent,!cobigen-javaplugin-parent,!cobigen-openapiplugin-parent,!cobigen-templateengines -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  run-core-systemtest:
    needs: build-and-test-plugins
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [8, 11]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Enable git support for long paths on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - uses: actions/checkout@v2

      - name: Set up OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.javaVersion }}
          settings-path: ${{ github.workspace }}

      - name: Run Core Systemtest
        shell: bash
        run: |
          mvn test -f cobigen/cobigen-core-systemtest -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  build-and-test-eclipse-plugin:
    needs: build-plugins-p2
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [8, 11]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - uses: actions/cache@v2.1.5
        with:
          path: ./**/target/repository/
          key: p2-${{ github.sha }}

      - name: Enable git support for long paths on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - uses: actions/checkout@v2

      - name: Set up OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.javaVersion }}
          settings-path: ${{ github.workspace }}

      - name: Build Plugins
        uses: GabrielBB/xvfb-action@v1.5
        with:
          run: |
            mvn verify -f cobigen-eclipse -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  build-and-test-maven-plugin:
    needs: build-and-test-plugins
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [8, 11]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Enable git support for long paths on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - uses: actions/checkout@v2

      - name: Set up OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.javaVersion }}
          settings-path: ${{ github.workspace }}

      - name: Build & Test Maven Plugin
        shell: bash
        run: |
          mvn verify -f cobigen-maven -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  build-and-test-cli:
    needs: build-and-test-plugins
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [8, 11]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository/com/devonfw/cobigen
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Enable git support for long paths on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - uses: actions/checkout@v2

      - name: Set up OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.javaVersion }}
          settings-path: ${{ github.workspace }}

      - name: Build & Test CLI
        shell: bash
        run: |
          mvn verify -f cobigen-cli -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
